<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="exampleTest-20171208134831" tests="2" time="0.001">
	<testcase classname="exampleTest" name="testPlusSuccess" time="0.000"/>
	<testcase classname="exampleTest" name="testMinusFail" time="0.001">
		<error message="1 != 3" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "exampleTest.py", line 28, in testMinusFail
    self.assertEqual(self.exampleClass.Minus(2, 1), 3)
AssertionError: 1 != 3
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
